### ISSUE TITLE
Add possibility to mock `didSet` and `willSet`.

### ISSUE THREAD

**Issue by FilipDolnik** [SwiftKit/Cuckoo#35]

**Comment by TadeasKriz** [comment]
These are only listeners, how would you mock them?

**Comment by FilipDolnik** [comment]
Just like get and set. You only need to generate proper mocks.

**Comment by TadeasKriz** [comment]
You cant have both `get` + `set` and `didSet` + `willSet` declared.

**Comment by TadeasKriz** [comment]
What would be the purpose to mock `didSet` and `willSet`?

**Comment by FilipDolnik** [comment]
Because you can have properties which have didSet and willSet? 
Ok I didn`t know about that, but it may be possible if you call then in the set manually.
Only problem is what happens when didSet is declared in the base class. But we have to solve this either way.

**Comment by TadeasKriz** [comment]
So what that you have properties with `didSet` and `willSet`? They are just listeners on the `set`. So you have to mock `set` anyway. I still don't see why would you need to stub `didSet` and `willSet` instead of just the `set` itself?

You are stubbing in order to provide some dumb implementation of things that could be called from the outside. `didSet` and `willSet` cannot be called from the outside so there is no reason to stub them.

**Comment by FilipDolnik** [comment]
And if the real implementation exists? You need a way to decide if to execute it or not.

**Comment by TadeasKriz** [comment]
Execute what? If there is a real implementation, you would do `mock(xx.set).thenCallRealMethod` which will in turn do basically `super.xxx = newValue`. You never can do `super.xx.didSet(newValue)` in Swift.
