### ISSUE TITLE
Run script not downloading with CocoaPods

### ISSUE THREAD

**Issue by akashgupta88** [SwiftKit/Cuckoo#51]
I have recently tried installing Cuckoo with CocoaPods and followed the steps exactly as mentioned in the README. However, when the test build reaches the Run Script execution, the build fails with the following error: 

> /Users/akashgupta/Library/Developer/Xcode/DerivedData/MyProject-fuzogkowjcqugqfvytlccugpuhiw/Build/Intermediates/MyProject.build/Debug-iphonesimulator/MyProjectTests.build/Script-5A21C7261D39029400856AD6.sh: line 11: /Users/akashgupta/Desktop/Workspace/MyProject/Pods/Cuckoo/run: No such file or directory

Apparently, the run script file does not exist. Perhaps it does not get downloaded via CocoaPods?

Moreover, I tried creating the run script file myself, but that led to another failure with the error:

> /Users/akashgupta/Library/Developer/Xcode/DerivedData/MyProject-fuzogkowjcqugqfvytlccugpuhiw/Build/Intermediates/MyProject.build/Debug-iphonesimulator/MyProjectTests.build/Script-5A21C7261D39029400856AD6.sh: line 11: /Users/akashgupta/Desktop/Workspace/MyProject/Pods/Cuckoo/run: Permission denied

Is there something I am missing while integrating this framework?

**Comment by TadeasKriz** [comment]
Hi, what version of Cuckoo are you using? Could you check the directory `/Users/akashgupta/Desktop/Workspace/MyProjects/Pods/Cuckoo` and see if there is a `run` file?

If you create the `run` file by yourself, you have to do `chmod +x run`, to allow running it. That's why you get the `Permission denied`.

Anyway, it's strange that it does not get downloaded. I suspect you might have an older version of Cuckoo.

**Comment by akashgupta88** [comment]
I have just put down `pod 'Cuckoo'` in the PodFile and it has downloaded v0.4.0. Maybe the PodSpec needs to be updated? A quick `pod update` has now downloaded v0.6.0 😃, where the run script is showing.

I had earlier got the run file to execute by changing the permissions as you had mentioned.
